server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: parish-service
          uri: lb://PARISH-SERVICE
          predicates:
            - Path=/parishes/**
        - id: priest-service
          uri: lb://PRIEST-SERVICE
          predicates:
            - Path=/priests/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true