server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: priest-in-parish-route
          uri: lb://PRIEST-SERVICE
          predicates:
            - Path=/parishes/*/priests/**
          order: 1
        - id: parish-service-route
          uri: lb://PARISH-SERVICE
          predicates:
            - Path=/parishes/**
          order: 2
        - id: priest-service-route
          uri: lb://PRIEST-SERVICE
          predicates:
            - Path=/priests/**
          order: 3
  

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true